<a href="https://colab.research.google.com/github/aravind309/blogs/blob/main/Simple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**Importing** **Libraries**
---

NumPy is used to perform a  variety of mathematical operations on arrays. It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices.

Scikit-learn (Sklearn) is the most useful and robust library for machine learning in Python. It provides a selection of efficient tools for machine learning and statistical modeling including classification, regression, clustering and dimensionality reduction via a consistence interface in Python.

In [29]:
import numpy as np
from sklearn.linear_model import LinearRegression

**Input of train dataset**

Input(Independent variables) are defined as 2d arrays. 2d arrays indicate that input has 2 features. In other words output y is dependent on 2 features

In [30]:
X = np.array([[1, 1], [2, 2], [3, 3], [4, 4]])
X

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

**Output of train dataset**

Out output Y is defined as a linear function of f. Let us assume for time being that Y can be calulated as y = 1 * x0 + 2 * x1 + 3. Note that this computation is just to replicate the train dataset. In real world our machine learing will predict these values using the train dataset

In [31]:
y = np.dot(X, np.array([1, 2]) ) + 2
y

array([ 5,  8, 11, 14])


**Fit train data to Linear Regression curve**

LinearRegression fits a linear model with coefficients w = (w1, …, wp) to minimize the residual sum of squares between the observed targets in the dataset, and the targets predicted by the linear approximation.

In [32]:
reg = LinearRegression().fit(X, y)

**Prediction on our test data**

Above trained regression will be used to predict the output on test data. Here our test data is [5, 5]

In [33]:
reg.predict(np.array([[5, 5]]))

array([17.])

**Printing the cofficients**

coef_array of shape (n_features, )
Estimated coefficients for the linear regression problem. In our case we passed two features, so we get two weights w0, w1. 

intercept_ It is the Independent term in the linear model. In other words it is the constant number we added to our Input.


In [34]:
print("Weights : ", reg.coef_)

Weights :  [1.5 1.5]


In [35]:
print(" Intercept : ", reg.intercept_)

 Intercept :  2.0000000000000018
